### ISSUE TITLE
Cannot upload .mmcif to PDB

### ISSUE THREAD

**Issue by helgepat** [keitaroyam/servalcat#11]
Hi,

I am in the process of uploading our models to the PDB, assuming that the provided .mmcif file from Servalcat would be suitable, but I am getting the following error:

```
ERROR: For '_atom_site.label_asym_id' and '_atom_site.auth_asym_id' fields, only
       alphanumeric values (A-Z, 0-9, a-z) are allowed. The values ( 'A-p', 'B-p',
       'C-p', 'E-p', 'G-p', 'I-p', 'J-p', 'M-p', 'N-p', 'S-p', 'V-1', 'V-2', 'W-0',
       'W-01', 'W-02', 'W-03', 'W-04', 'W-05', 'W-06', 'W-07', 'W-08', 'W-09', 'W-0A',
       'W-0B', 'W-0C', 'W-0D', 'W-0E', 'W-0F', 'W-0G', 'W-0H', 'W-0I', 'W-0J', 'W-0K',
       'W-0L', 'W-0M', 'W-0N', 'W-0O', 'W-0P', 'W-0Q', 'W-0R', 'W-0S', 'W-0T', 'W-0U',
       'W-0V', 'W-0W', 'W-0X', 'W-1', 'W-2', 'W-3', 'W-4', 'W-5', 'W-6', 'W-7', 'W-8',
       'W-9', 'W-w' ) are not allowed.
```

Is there a way around this error? We have our waters and other solvent in Chain "W", but it seems every chain in the model has the "*-p" denominator?

I just tried running PDB-extract on the .pdb from Servalcat and this seems to work.

**Comment by keitaroyam** [comment]
I am sorry about this! Yes, refined.mmcif is supposed to be suitable for the PDB deposition. Gemmi 0.5.8 has introduced 'A-p' style _atom_site.label_asym_id (that means chain A, polymer entity) and it turned out prohibited by the PDB. It has been already fixed, but you would need the latest code of gemmi, servalcat, and refmac. So it will be officially fixed in the next release.

Can you use refined.pdb for the deposition? I think OneDep still accepts the PDB format for cryo-EM SPA entries. PDB-extract may be ok, but not sure.

**Comment by helgepat** [comment]
Yes, I am using .pdb with PDB-Extract now. Looking at it this seems to be my smallest problem, I have 15 models of ribosomal subunits to upload all with modifications... quite a lot of copy/paste with all those modified residues... so running PDB-Extract actually helps as it at least gives me the modified residues which I can search-replace in my parental sequence ;)
