### ISSUE TITLE
Error while running servalcat

### ISSUE THREAD

**Issue by simonmiljan** [keitaroyam/servalcat#5]
Hi, I recently updated gemmi (0.5.7) and servalcat, but I encountered an "unexpected chirality" error while trying to calculate Fo-Fc map. 
I checked the pdb file and could not detect where the unexpected chirtality is coming from. Could you help with this?

Best,

Miljan

[Servalcat-error.txt](https://github.com/keitaroyam/servalcat/files/9658910/Servalcat-error.txt)

**Comment by keitaroyam** [comment]
Thanks for your message! It seems a very old Servalcat (0.1.50) is being used. Could you try the latest Servalcat (0.2.122)? Actually, this "chirality" problem was fixed in gemmi last year - so most likely you are not using gemmi 0.5.7. Please check your installation.

If I recall correctly, this "." chirality was seen in an old monomer library. I would also encourage you to use CCP4 8 if an older version is used.

**Comment by simonmiljan** [comment]
You were right. Although I installed the latest servalcat version (and
gemmi), for some reason an older servalcat embedded in old ccpem was
invoked.
Thank you!
Best,
Miljan
